code/.idea/misc.xml
code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/test/java/ca/ualberta/ishelf/BookTest.java

This is the Book class code with tests

Jscottgray

---

code/app/src/main/java/ca/ualberta/ishelf/Borrow.java
code/app/src/main/java/ca/ualberta/ishelf/Rating.java
code/app/src/main/java/ca/ualberta/ishelf/Request.java
code/app/src/test/java/ca/ualberta/ishelf/BorrowTest.java
code/app/src/test/java/ca/ualberta/ishelf/RatingTest.java
code/app/src/test/java/ca/ualberta/ishelf/RequestTest.java

Reverts CMPUT301W19T03/iShelf#5

Revert "Revert "Mehrab1""

---

code/.idea/misc.xml
code/app/src/main/java/ca/ualberta/ishelf/Notification.java
code/app/src/test/java/ca/ualberta/ishelf/NotificationTest.java

added notification class and tests

Faisal branch

---

code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/main/java/ca/ualberta/ishelf/MainActivity.java
code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/test/java/ca/ualberta/ishelf/BookTest.java

made changes to master, to collaborate all different branches

edited rating class

---

code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/test/java/ca/ualberta/ishelf/BookTest.java
code/build.gradle

Fixed User, Book and UserTest and BookTest. All tests inside them are now successful.

fixed user and book, along with their tests

---

code/app/src/main/java/ca/ualberta/ishelf/Database.java
code/app/src/main/java/ca/ualberta/ishelf/SignInActivity.java
code/app/src/main/res/layout/activity_sign_in.xml

Made a pull request for signin, now its just entering a username and it uses it without any password or authentication as using google login only worked in my Android Studio because it uses my key.  Also, made a connect() method in Database class that returns the Firebase ref object that is already connected so we don’t have to make it and add the link in every class.
`Firebase ref = new Database().connect(this);`

username login and database connect

---

code/app/src/main/java/ca/ualberta/ishelf/Database.java
code/app/src/main/java/ca/ualberta/ishelf/EditBookActivity.java
code/app/src/main/java/ca/ualberta/ishelf/EditProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/SignInActivity.java
code/app/src/main/java/ca/ualberta/ishelf/ViewProfileActivity.java

1- Fixed firebase in edituser and showing the edited user when going back to viewProfile
2- Updated add book to firebase in EditBookActivity
3- Fixed methods in Database class (addUser, deleteUser, addBook, deleteBook, addNotification, deleteNotification). Now we can use them. (Not getters from firebase)

firebase for edit user and database

---

code/app/src/main/AndroidManifest.xml
code/app/src/main/java/ca/ualberta/ishelf/EditProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/Rating.java
code/app/src/main/java/ca/ualberta/ishelf/RequestAdapter.java
code/app/src/main/java/ca/ualberta/ishelf/RequestFragment.java
code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/main/java/ca/ualberta/ishelf/ViewProfileActivity.java
code/app/src/main/res/layout/activity_edit_profile.xml
code/app/src/main/res/layout/activity_view_profile.xml

Added a 5-star representation of a user's overall rating on the profile screen. A few other small fixes as well.

added star representation of user's overall rating

---

code/app/src/main/java/ca/ualberta/ishelf/MainActivity.java
code/app/src/main/java/ca/ualberta/ishelf/ViewProfileActivity.java
code/app/src/main/res/layout/appbar.xml

Restores deleted functionality: Links User icon in appbar to signed-in user's profile

Jeremy linktoprofile

---

code/app/build.gradle
code/app/src/androidTest/java/ca/ualberta/ishelf/ViewProfileTest.java
code/app/src/main/java/ca/ualberta/ishelf/EditProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/MainActivity.java
code/app/src/main/java/ca/ualberta/ishelf/SignInActivity.java
code/app/src/main/res/layout/activity_sign_in.xml

added new Register button on login activity so someone can add a new account

added Register new account functionality

---

code/app/src/main/java/ca/ualberta/ishelf/NotificationActivity.java
code/app/src/main/java/ca/ualberta/ishelf/NotificationAdapter.java

Implemented getNotification() to get notifications from firebase
*For testing* I commented the lines to check the username so now it shows all notifications for all users

get notifications from firebase

---

code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/Database.java
code/app/src/main/java/ca/ualberta/ishelf/EditBookActivity.java
code/app/src/main/java/ca/ualberta/ishelf/MyAdapter.java
code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/main/java/ca/ualberta/ishelf/myBooksFragment.java

Cleaned MyBooksFragment.
Gets “My Books” from firerbase. 
Fixed filters in “My Books”
Fixed edit book with firebase
Added delete book and its firebase
Added add/delete book from user list of books and its firebase

Pull request Fixes/rmnattas

---

code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/main/java/ca/ualberta/ishelf/myBooksFragment.java
code/app/src/test/java/ca/ualberta/ishelf/UserTest.java

i re-arranged some stuff too, deleted bulky comments and old code

changed user and user tests to match

---

code/app/src/main/java/ca/ualberta/ishelf/Book.java

didn't set status to available when creating a book. Fixed - now tests work again

Fixed book so that the tests don't fail

---

code/app/src/main/java/ca/ualberta/ishelf/EditProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/ViewProfileActivity.java

Just added a bit more comments, no rush to merge

Added more comments

---

code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/User.java
code/app/src/main/res/layout/activity_book_profile.xml

remove book from borrowed books when returned 

---

code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java

delete all requests when a book is deleted

---

code/app/src/main/res/drawable/roundedbutton.xml
code/app/src/main/res/drawable/shape.xml
code/app/src/main/res/layout/activity_main.xml
code/app/src/main/res/layout/fragment_request.xml
code/app/src/main/res/layout/my_book.xml

background gradient added, filter icon changed

changed UI

---

code/app/src/main/java/ca/ualberta/ishelf/myBooksFragment.java

show new book in myBooks after adding it 

---

code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/MapsActivity.java
code/app/src/main/java/ca/ualberta/ishelf/RatingActivity.java
code/app/src/main/java/ca/ualberta/ishelf/Request.java
code/app/src/main/res/layout/activity_book_profile.xml
code/app/src/main/res/layout/activity_rating.xml

Borrower can view map of where the pick up location is.
To do this they access the map via a button in the book profile.
To Do: retrieve the relevant request from firebase using the book name and signed in username
Also in this pull request is Rating Activity - this is not connected to the other activities yet.

Jeremy maps

---

code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/ScanActivity.java

Verify proccess/mehrab

---

code/app/build.gradle
code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/BorrowAdapter.java
code/app/src/main/java/ca/ualberta/ishelf/GalleryActivity.java
code/app/src/main/java/ca/ualberta/ishelf/GalleryAdapter.java
code/app/src/main/java/ca/ualberta/ishelf/MyAdapter.java
code/app/src/main/java/ca/ualberta/ishelf/MyAppGlideModule.java
code/app/src/main/java/ca/ualberta/ishelf/ViewImageActivity.java
code/app/src/main/res/layout/activity_book_profile.xml
code/app/src/main/res/layout/activity_view_image.xml
code/app/src/main/res/layout/borrow_book_item.xml

improved image holding (using Firebase Storage) and books have book covers now

Images redone/faisal

---

code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/main/java/ca/ualberta/ishelf/BookProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/MainActivity.java
code/app/src/main/java/ca/ualberta/ishelf/Request.java
code/app/src/main/res/layout/activity_book_profile.xml
code/app/src/main/res/layout/activity_rating.xml
code/app/src/main/res/layout/activity_sign_in.xml
code/app/src/main/res/layout/activity_view_profile.xml
code/app/src/main/res/layout/review_item.xml

Bug fixes.
Rating bars show granularity of 0.5 instead of 1.0
Text of review boxes are now hints instead of text
The Borrower is now asked to review the book
Log in button is now on the right side (register is now on left)

Misc Bug Fixes

---

code/app/src/main/java/ca/ualberta/ishelf/Book.java
code/app/src/main/java/ca/ualberta/ishelf/EditProfileActivity.java
code/app/src/main/java/ca/ualberta/ishelf/ViewProfileActivity.java

When a user updates their profile and they had reviews, it would crash the app
This is fixed by passing only the username instead of the user object

Edit Profile Bug
